CREATE TABLE email(
    emain_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(200),
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE email
ADD COLUMN email VARCHAR(200),
ADD COLUMN phone VARCHAR(10);